// <auto-generated />
using ImportacionesDC.Models.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpresaDC.Migrations
{
    [DbContext(typeof(DbContextImportaciones))]
    [Migration("20200902051722_Se agrego todo")]
    partial class Seagregotodo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImportacionesDC.Models.Entities.Cliente", b =>
                {
                    b.Property<int>("NumeroCasillero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("DireccionEntrega")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NombreCliente")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NumeroCasillero");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("ImportacionesDC.Models.Entities.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NombreEstado")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstado");

                    b.ToTable("estados");
                });

            modelBuilder.Entity("ImportacionesDC.Models.Entities.Paquete", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Casillero")
                        .HasColumnName("CasilleroCliente")
                        .HasColumnType("int");

                    b.Property<int>("Empresa")
                        .HasColumnName("EmpresaTransportadora")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Guia")
                        .IsRequired()
                        .HasColumnName("GuiaColombia")
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Tracking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Valor")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.ToTable("paquetes");
                });

            modelBuilder.Entity("ImportacionesDC.Models.Entities.TipoMercancia", b =>
                {
                    b.Property<int>("IdTipoMercancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("TipoMercancia")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTipoMercancia");

                    b.ToTable("mercancias");
                });

            modelBuilder.Entity("ImportacionesDC.Models.Entities.Transportadora", b =>
                {
                    b.Property<int>("IdTransportadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("NombreTransportadora")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTransportadora");

                    b.ToTable("transportadoras");
                });
#pragma warning restore 612, 618
        }
    }
}
